# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Photo', models.ImageField(upload_to='Blog_Photo')),
                ('Blog_Title', models.TextField()),
                ('Blog_Composition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Fashion_Photo', models.ImageField(upload_to='Fashion/')),
            ],
        ),
        migrations.CreateModel(
            name='My_Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home_Page', models.ImageField(upload_to='MyPhoto/')),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Poetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poem_Title', models.TextField()),
                ('Poem_Composition', models.TextField()),
                ('Poem_Photo', models.ImageField(upload_to='Poetry_Photos/')),
            ],
        ),
    ]
