# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheAfrodesiac', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='My_Photo',
        ),
        migrations.AddField(
            model_name='blog',
            name='Date_Posted',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fashion',
            name='Date_Posted',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fashion',
            name='Fashion_Title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poetry',
            name='Date_Posted',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
    ]
